apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-azure-workload-identity
  annotations:
    meta.crossplane.io/maintainer: Livewyer <bowen@livewyer.com>
    meta.crossplane.io/source: https://github.com/livewyer-ops/crossplane-configuration-azure-workload-identity
    meta.crossplane.io/license: MIT License
    meta.crossplane.io/description: Crossplane Composite Resource Definitions (XRDs) package for creating Workload Identity in Azure.
    meta.crossplane.io/readme: ""
spec:
  crossplane:
    version: ">=v2.0.2"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-family-azure
      version: ">=v2"
    - provider: xpkg.upbound.io/upbound/provider-kubernetes
      version: ">=v1"
    - function: xpkg.upbound.io/upbound/function-go-templating
      version: ">=v0.10.0"
    - function: xpkg.upbound.io/upbound/function-auto-ready
      version: ">=v0.5.0"
