apiVersion: azure.livewyer.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: simple-example
  namespace: test
  annotations:
    crossplane.io/composition-resource-name: workloadidentity.azure.livewyer.io/simple-example
    test-annotation: "true"
  labels:
    test-label: "true"
spec:
  forProvider:
    location: eastus
    resourceGroupName: example-group
    serviceAccountName: simple-example
    oidcIssuerURL: https://eastus.oic.prod-aks.azure.com/00000000-0000-0000-0000-000000000000/11111111-1111-1111-1111-111111111111/
    roleAssignments:
      - roleDefinitionName: Read Only
        scope: /subscriptions/xxxx-xxxx-xxxx
      - roleDefinitionName: Owner
        scope: /subscriptions/yyyy-yyyy-yyyy
      - roleDefinitionName: CustomRole1
        scope: /subscriptions/xxxx-xxxx-xxxx
        permissions:
          - dataActions:
              - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read
            notActions:
              - Microsoft.Network/loadBalancers/read
      - roleDefinitionName: CustomRole2
        scope: /subscriptions/yyyy-yyyy-yyyy
        permissions:
          - actions:
              - Microsoft.Network/applicationGateways/read
              - Microsoft.Network/networkSecurityGroups/read
    tags:
      name: simple-example
      env: test
