apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: workloadidentity.azure.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: azure.livewyer.io/v1alpha1
    kind: WorkloadIdentity
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
