apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: workloadidentities.azure.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: azure.livewyer.io/v1alpha1
    kind: WorkloadIdentity
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $id := .observed.composite.resource.metadata.name -}}
            {{ $ns := default "default" $.observed.composite.resource.metadata.namespace }}
            {{ $spec := .observed.composite.resource.spec -}}

            ---
            {{- if ne $ns "default" }}

            apiVersion: v1
            kind: Namespace
            metadata:
              name: {{ $ns }}
              annotations:
                {{ setResourceNameAnnotation (printf "namespace.workloadidentity.azure.livewyer.io/%s" $id) }}

            {{- end }}
            ---

            apiVersion: managedidentity.azure.m.upbound.io/v1beta1
            kind: UserAssignedIdentity
            metadata:
              name: {{ $id }}
              namespace: {{ $ns }}
              annotations:
                {{ setResourceNameAnnotation (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id) }}
              labels:
                azure.livewyer.io/workloadidentity: {{ $id }}
                managedidentity.azure.livewyer.io/userassignedidentity: {{ $id }}
            spec:
              {{- if $spec.providerConfigRef }}
              providerConfigRef: {{ toJson $spec.providerConfigRef }}
              {{- end }}
              {{- if $spec.deletionPolicy }}
              deletionPolicy: {{ $spec.deletionPolicy }}
              {{- end }}
              {{- if $spec.managementPolicies }}
              managementPolicies: {{ toJson $spec.managementPolicies }}
              {{- end }}
              {{- if $spec.publishConnectionDetailsTo }}
              publishConnectionDetailsTo: {{ toJson $spec.publishConnectionDetailsTo }}
              {{- end }}
              {{- if $spec.writeConnectionSecretsToNamespace }}
              writeConnectionSecretsToNamespace: {{ $spec.writeConnectionSecretsToNamespace }}
              {{- end }}
              forProvider:
                name: {{ $id }}
                location: {{ $spec.forProvider.location }}
                resourceGroupName: {{ $spec.forProvider.resourceGroupName }}
                {{- if $spec.forProvider.tags }}
                tags: {{ toJson $spec.forProvider.tags }}
                {{- end }}

            ---

            apiVersion: managedidentity.azure.m.upbound.io/v1beta1
            kind: FederatedIdentityCredential
            metadata:
              name: {{ $id }}
              namespace: {{ $ns }}
              annotations:
                {{ setResourceNameAnnotation (printf "federatedidentitycredential.managedidentity.azure.livewyer.io/%s" $id) }}
              labels:
                azure.livewyer.io/workloadidentity: {{ $id }}
                managedidentity.azure.livewyer.io/federatedidentitycredential: {{ $id }}
            spec:
              {{- if $spec.providerConfigRef }}
              providerConfigRef: {{ toJson $spec.providerConfigRef }}
              {{- end }}
              {{- if $spec.deletionPolicy }}
              deletionPolicy: {{ $spec.deletionPolicy }}
              {{- end }}
              {{- if $spec.managementPolicies }}
              managementPolicies: {{ toJson $spec.managementPolicies }}
              {{- end }}
              {{- if $spec.publishConnectionDetailsTo }}
              publishConnectionDetailsTo: {{ toJson $spec.publishConnectionDetailsTo }}
              {{- end }}
              {{- if $spec.writeConnectionSecretsToNamespace }}
              writeConnectionSecretsToNamespace: {{ $spec.writeConnectionSecretsToNamespace }}
              {{- end }}
              forProvider:
                resourceGroupName: {{ $spec.forProvider.resourceGroupName }}
                audience:
                  - api://AzureADTokenExchange
                issuer: {{ $spec.forProvider.oidcIssuerURL }}
                parentIdRef:
                  name: {{ $id }}
                  namespace: {{ $ns }}
                subject: {{ printf "system:serviceaccount:%s:%s" $ns $id }}

            ---
            {{- range $roleAssign := $spec.forProvider.roleAssignments }}
            {{- $roleId := printf "%s_%s_%s" $id (replace "/subscriptions/" "" $roleAssign.scope) $roleAssign.roleDefinitionName }}
            {{- if $roleAssign.permissions }}
            ---

            apiVersion: authorization.azure.m.upbound.io/v1beta1
            kind: RoleDefinition
            metadata:
              name: {{ $roleId }}
              namespace: {{ $ns }}
              annotations:
                {{ setResourceNameAnnotation (printf "roledefinition.authorization.azure.livewyer.io/%s" $roleId) }}
              labels:
                azure.livewyer.io/workloadidentity: {{ $id }}
                authorization.azure.livewyer.io/roledefinition: {{ $roleId }}
                azure.livewyer.io/subscription: {{ replace "/subscriptions/" "" $roleAssign.scope }}
            spec:
              {{- if $spec.providerConfigRef }}
              providerConfigRef: {{ toJson $spec.providerConfigRef }}
              {{- end }}
              {{- if $spec.deletionPolicy }}
              deletionPolicy: {{ $spec.deletionPolicy }}
              {{- end }}
              {{- if $spec.managementPolicies }}
              managementPolicies: {{ toJson $spec.managementPolicies }}
              {{- end }}
              {{- if $spec.publishConnectionDetailsTo }}
              publishConnectionDetailsTo: {{ toJson $spec.publishConnectionDetailsTo }}
              {{- end }}
              {{- if $spec.writeConnectionSecretsToNamespace }}
              writeConnectionSecretsToNamespace: {{ $spec.writeConnectionSecretsToNamespace }}
              {{- end }}
              forProvider:
                name: {{ $roleAssign.roleDefinitionName }}
                {{- if $roleAssign.scopeRef }}
                scopeRef: {{ toJson $roleAssign.scopeRef }}
                {{- else }}
                scope: {{ $roleAssign.scope }}
                {{- end }}
                {{- if $roleAssign.assignableScopes }}
                assignableScopes: {{ $roleAssign.assignableScopes }}
                {{- end }}
                {{- if $roleAssign.assignableScopesRefs }}
                assignableScopesRefs: {{ toJson $roleAssign.assignableScopesRefs }}
                {{- end }}
                {{- if $roleAssign.description }}
                description: {{ $roleAssign.description }}
                {{- end }}
                {{- if $roleAssign.roleDefinitionId }}
                roleDefinitionId: {{ $roleAssign.roleDefinitionId }}
                {{- end }}
                permissions: {{ toJson $roleAssign.permissions }}

            ---
            {{- end }}
            ---

            apiVersion: authorization.azure.m.upbound.io/v1beta1
            kind: RoleAssignment
            metadata:
              name: {{ $roleId }}
              namespace: {{ $ns }}
              annotations:
                {{ setResourceNameAnnotation (printf "roleassignment.authorization.azure.livewyer.io/%s" $roleId) }}
              labels:
                azure.livewyer.io/workloadidentity: {{ $id }}
                authorization.azure.livewyer.io/roleassignment: {{ $roleId }}
                azure.livewyer.io/subscription: {{ replace "/subscriptions/" "" $roleAssign.scope }}
            spec:
              {{- if $spec.providerConfigRef }}
              providerConfigRef: {{ toJson $spec.providerConfigRef }}
              {{- end }}
              {{- if $spec.deletionPolicy }}
              deletionPolicy: {{ $spec.deletionPolicy }}
              {{- end }}
              {{- if $spec.managementPolicies }}
              managementPolicies: {{ toJson $spec.managementPolicies }}
              {{- end }}
              {{- if $spec.publishConnectionDetailsTo }}
              publishConnectionDetailsTo: {{ toJson $spec.publishConnectionDetailsTo }}
              {{- end }}
              {{- if $spec.writeConnectionSecretsToNamespace }}
              writeConnectionSecretsToNamespace: {{ $spec.writeConnectionSecretsToNamespace }}
              {{- end }}
              forProvider:
                name: {{ $roleAssign.roleDefinitionName }}
                scope: {{ $roleAssign.scope }}
                principalId: {{ dig "status" "atProvider" "principalId" "" (getComposedResource . (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id)) }}
                {{- if $roleAssign.description }}
                description: {{ $roleAssign.description }}
                {{- end }}
                {{- if $roleAssign.principalType }}
                principalType: {{ $roleAssign.principalType }}
                {{- end }}
                {{- if $roleAssign.condition }}
                condition: {{ $roleAssign.condition }}
                {{- end }}
                {{- if $roleAssign.conditionVersion }}
                conditionVersion: {{ $roleAssign.conditionVersion }}
                {{- end }}
                {{- if $roleAssign.permissions }}
                roleDefinitionIdRef:
                  name: {{ $roleId }}
                  namespace: {{ $ns }}
                {{- else }}
                roleDefinitionName: {{ $roleAssign.roleDefinitionName }}
                {{- end }}

            ---
            {{- end }}
            {{- if $spec.forProvider.serviceAccountName }}
            ---

            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: {{ $spec.forProvider.serviceAccountName }}
              namespace: {{ $ns }}
              annotations:
                {{ setResourceNameAnnotation (printf "serviceaccount.workloadidentity.azure.livewyer.io/%s" $spec.forProvider.serviceAccountName) }}
                azure.workload.identity/client-id: {{ default (toString "''") (getComposedResource . (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id)).status.atProvider.clientId }}
                azure.workload.identity/tenant-id: {{ default (toString "''") (getComposedResource . (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id)).status.atProvider.tenantId }}
                azure.workload.identity/service-account-token-expiration: {{ default (toString "'86400'") $spec.forProvider.serviceAccountTokenExpiration }}
              labels:
                azure.livewyer.io/workloadidentity: {{ $id }}

            ---
            {{- end }}
            ---

            apiVersion: {{ .observed.composite.resource.apiVersion }}
            kind: {{ .observed.composite.resource.kind }}
            metadata:
              labels:
                azure.livewyer.io/workloadidentity: {{ $id }}
            status:
              atProvider:
                location: {{ default "" (getComposedResource . (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id)).status.atProvider.location }}
                resourceGroupName: {{ default "" (getComposedResource . (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id)).status.atProvider.resourceGroupName }}
                oidcIssuerURL: {{ default "" (getComposedResource . (printf "federatedidentitycredential.managedidentity.azure.livewyer.io/%s" $id)).status.atProvider.issuer }}
                clientId: {{ default "" (getComposedResource . (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id)).status.atProvider.clientId }}
                tenantId: {{ default "" (getComposedResource . (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id)).status.atProvider.tenantId }}
                principalId: {{ default "" (getComposedResource . (printf "userassignedidentity.managedidentity.azure.livewyer.io/%s" $id)).status.atProvider.principalId }}
                roleAssignments:
                  {{- range $roleAssign := $spec.forProvider.roleAssignments }}
                  {{- $roleId := printf "%s_%s_%s" $id (replace "/subscriptions/" "" $roleAssign.scope) $roleAssign.roleDefinitionName }}
                  {{- if $roleAssign.permissions }}
                  - scope: {{ default "" (getComposedResource . (printf "roleassignment.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.scope }}
                    roleDefinitionId: {{ default "" (getComposedResource . (printf "roledefinition.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.id }}
                    roleDefinitionName: {{ default "" (getComposedResource . (printf "roledefinition.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.name }}
                    roleAssignmentId: {{ default "" (getComposedResource . (printf "roleassignment.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.id }}
                    roleAssignmentName: {{ default "" (getComposedResource . (printf "roleassignment.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.name }}
                    permissions: {{ default (list) (getComposedResource . (printf "roledefinition.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.permissions }}
                  {{- else }}
                  - scope: {{ default "" (getComposedResource . (printf "roleassignment.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.scope }}
                    roleDefinitionName: {{ $roleAssign.roleDefinitionName }}
                    roleAssignmentId: {{ default "" (getComposedResource . (printf "roleassignment.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.id }}
                    roleAssignmentName: {{ default "" (getComposedResource . (printf "roleassignment.authorization.azure.livewyer.io/%s" $roleId)).status.atProvider.name }}
                  {{- end }}
                  {{- end }}

            ---

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
